version: '3'
services:
  articleservice:
    image: joowojr/article-service:latest
    container_name: articleservice
    ports:
      - 8081:8080
    depends_on:
      - eureka
      - gateway
    networks:
      - msa-network
    restart: on-failure

  messageservice:
    image: joowojr/message-service:latest
    container_name: messageservice
    ports:
      - 8082:8080
    depends_on:
      - eureka
      - gateway
    networks:
      - msa-network
    restart: on-failure

  transactionservice:
    image: joowojr/transaction-service:latest
    container_name: transactionservice
    ports:
      - 8083:8080
    depends_on:
      - eureka
      - gateway
    networks:
      - msa-network
    restart: on-failure

  userservice:
    image: joowojr/user-service:latest
    container_name: userservice
    ports:
      - 8084:8080
    depends_on:
      - eureka
      - gateway
    networks:
      - msa-network
    restart: on-failure
  joinservice:
    image: joowojr/join-service:latest
    container_name: joinservice
    ports:
      - 8085:8080
    depends_on:
      - eureka
      - gateway
    networks:
      - msa-network
    restart: on-failure
networks:
  msa-network:
    external: true