version: '3'
services:
  joinservice:
    image: joowojr/join-service:latest
    container_name: joinservice
    ports:
      - 8085:8080
    depends_on:
      - eureka
      - gateway
      -
    networks:
      - msa-network
    restart: on-failure

networks:
  msa-network:
    external: true